FROM node:22-alpine
WORKDIR /app
ENV NODE_ENV=production

COPY package.json package-lock.json ./
COPY apps ./apps
COPY packages ./packages
COPY tsconfig.json tsconfig.base.json turbo.json ./
RUN npm install

COPY . .
CMD ["npm", "run", "scheduler", "-w", "@netk/market-fetcher"]
